/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IstitutiRouteImport } from './routes/istituti'
import { Route as IndexRouteImport } from './routes/index'

const IstitutiRoute = IstitutiRouteImport.update({
  id: '/istituti',
  path: '/istituti',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/istituti': typeof IstitutiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/istituti': typeof IstitutiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/istituti': typeof IstitutiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/istituti'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/istituti'
  id: '__root__' | '/' | '/istituti'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IstitutiRoute: typeof IstitutiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/istituti': {
      id: '/istituti'
      path: '/istituti'
      fullPath: '/istituti'
      preLoaderRoute: typeof IstitutiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IstitutiRoute: IstitutiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
